blank_issues_enabled: false
contact_links:
  - name: Others
    url: https://github.com/Kjuly/.github/blob/main/SUPPORT.md
    about: If you have any other questions or suggestions, email directly to dev@kjuly.com.

